// RUN: sclang --emit=ast %s 2>&1 | FileCheck %s

function_block expressions

begin
// CHECK: CodeSection

  "a".x := "b".x;
// CHECK-NEXT: ValueAssignment
// CHECK-NEXT:   BinaryExpression :=
// CHECK-NEXT:     BinaryExpression .
// CHECK-NEXT:       Symbol a
// CHECK-NEXT:       SimpleVariable x
// CHECK-NEXT:     BinaryExpression .
// CHECK-NEXT:       Symbol b
// CHECK-NEXT:       SimpleVariable x

end_function_block
