// RUN: sclang-gen --emit=mlir-std %s | FileCheck %s

// CHECK:      func @abs(%arg0: f32) -> f32
function abs : real

var_input
 in : real;
end_var;

begin

// CHECK: [[C0:%[a-z0-9]+]] = arith.constant 0.000000e+00 : f32
// CHECK: memref.store %arg0, [[INVAR:%[0-9]+]][] : memref<f32>

// CHECK: [[IN:%[0-9]+]] = memref.load [[INVAR]]
// CHECK: [[LT:%[0-9]+]] = arith.cmpf ult, [[IN]], [[C0]]
// CHECK: scf.if [[LT]] {
  if in < 0.0 then

// CHECK:   [[IN:%[0-9]+]] = memref.load [[INVAR]]
// CHECK:   [[NEG:%[0-9]+]] = arith.negf [[IN]] : f32
// CHECK:   memref.store [[NEG]], [[ABS:%[0-9]+]][] : memref<f32>
    abs := -in;

// CHECK: } else {
// CHECK:   [[IN:%[0-9]+]] = memref.load [[INVAR]]
// CHECK:   [[GT:%[0-9]+]] = arith.cmpf ugt, [[IN]], [[C0]]
// CHECK:   scf.if [[GT]] {
  elsif in > 0.0 then

// CHECK:     [[IN:%[0-9]+]] = memref.load [[INVAR]]
// CHECK:     memref.store [[IN]], [[ABS]][] : memref<f32>
    abs := in;

// CHECK:   } else {
  else

// CHECK: memref.store [[C0]], [[ABS]][] : memref<f32>
    abs := 0.0;

// CHECK:   }
// CHECK: }
  end_if;

// CHECK: [[RET:%[0-9]+]] = memref.load [[ABS]][] : memref<f32>
// CHECK: return [[RET]]
end_function
