// RUN: sclang-gen --emit=mlir-std %s | FileCheck %s


// CHECK-LABEL: @ret_implicit_void
// CHECK:       return
function ret_implicit_void : void
begin
  ;
end_function

// CHECK-LABEL: @ret_explicit_void
// CHECK:       return
function ret_explicit_void : void
begin
  return;
end_function

// NO-CHECK-LABEL: @ret_implicit_real
// NO-CHECK:       [[C1:[a-z0-9]+]] = constant 1.0 : f32
// NO-CHECK:       return [[C1]] : f32
function ret_implicit_real : real
begin
  ret_implicit_real := 1.0;
end_function

// NO-CHECK-LABEL: @ret_explicit_real
// NO-CHECK:       [[C1:[a-z0-9]+]] = constant 1.0 : f32
// NO-CHECK:       return [[C1]] : f32
function ret_explicit_real : real
begin
  ret_explicit_real := 1.0;
  return;
end_function

// NO-CHECK-LABEL: @ret_implicit_int
// NO-CHECK:       [[C1:[a-z0-9]+]] = constant 1 : i16
// NO-CHECK:       return [[C1]] : i16
function ret_implicit_int : int
begin
  ret_implicit_int := int#1;
  return;
end_function

// NO-CHECK-LABEL: @ret_explicit_int
// NO-CHECK:       [[C1:[a-z0-9]+]] = constant 1 : i16
// NO-CHECK:       return [[C1]] : i16
function ret_explicit_int : int
begin
  ret_explicit_int := int#1;
  return;
end_function
