// RUN: sclang --emit=mlir %s | FileCheck %s

// CHECK:      func @abs(%arg0: i16) -> i16
// CHECK-NEXT:   [[ABS:%[0-9]+]] = scl.tmpvar "abs" : memref<i16>
function abs : int

var_input
 in : INT;
end_var;

begin
// CHECK: [[C0:%[0-9]+]] = scl.constant 0 : i16
// CHECK: [[LT:%[0-9]+]] = scl.cmplt %arg0, [[C0]]
// CHECK: "scl.if"([[LT]])
  if in < 0 then

// CHECK: [[NEG:%[0-9]+]] = scl.negate %arg0
// CHECK: scl.store [[ABS]] : memref<i16> = [[NEG]]
    abs := -in;

// CHECK: scl.end
// CHECK: [[C0:%[0-9]+]] = scl.constant 0 : i16
// CHECK: [[GT:%[0-9]+]] = scl.cmpgt %arg0, [[C0]]
// CHECK: "scl.if"([[GT]])
  elsif in > 0 then

// CHECK: scl.store [[ABS]] : memref<i16> = %arg0
    abs := in;

// CHECK: scl.end
  else

// CHECK: [[C0:%[0-9]+]] = scl.constant 0 : i16
// CHECK: scl.store [[ABS]] : memref<i16> = [[C0]]
    abs := 0;

// CHECK: scl.end
  end_if;

// CHECK: scl.return [[ABS]] : memref<i16>
end_function
