language: cpp

os:
  - linux

# Use Ubuntu 18.04 LTS (Bionic) as the Linux testing environment.
dist: focal

branches:
  only:
    - main

jobs:
  include:
  - name: "GCC Release build"
    compiler: gcc
    env: BUILD_FLAGS="-DCMAKE_BUILD_TYPE=Release"
  - name: "CLANG Release build"
    compiler: clang
    env: BUILD_FLAGS="-DCMAKE_BUILD_TYPE=Release"
  - name: "Address/UB Sanitizer debug build"
    compiler: clang
    env: BUILD_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DLLVM_USE_SANITIZER='Address;Undefined'"

script:
  - git clone https://github.com/tali/llvm-project --depth 1
  - git clone . llvm-project/sclang
  - mkdir build && cd build
  - cmake -GNinja ../llvm-project/llvm
      -DLLVM_EXTERNAL_PROJECTS=sclang -DLLVM_ENABLE_PROJECTS="sclang;mlir"
      -DLLVM_ENABLE_ASSERTIONS=ON $BUILD_FLAGS
  - cmake --build . --target check-sclang

git:
  depth: 1

before_install:
  - sudo apt-get -yq --no-install-suggests --no-install-recommends install
      ninja-build
addons:
  apt:
    update: true
