// RUN: sclang-gen --emit=mlir %s | sclang-gen -x mlir --emit=mlir | FileCheck %s

// CHECK-LABEL: scl.function @abs(%arg0: !scl.real {scl.name = "in"}) -> !scl.real
// CHECK-DAG:   %abs = scl.tmpvar "abs" : !scl.address<!scl.real>
function abs : real

// CHECK-DAG:   %in = scl.tmpvar "in" : !scl.address<!scl.real>
// CHECK-DAG:   scl.store %in : !scl.address<!scl.real> = %arg0 : !scl.real
var_input
 in : real;
end_var;

begin
// CHECK-DAG:   [[C0:%cst[_0-9]*]] = scl.constant 0.000000e+00 : f32 -> !scl.real
// CHECK-DAG:   [[IN:%[0-9]+]] = scl.load %in
// CHECK-DAG:   [[LT:%[0-9]+]] = scl.cmplt [[IN]], [[C0]]
// CHECK:       scl.if [[LT]]
  if in < 0.0 then

// CHECK-DAG:   [[IN:%[0-9]+]] = scl.load %in
// CHECK-DAG:   [[NEG:%[0-9]+]] = scl.negate [[IN]]
// CHECK:       scl.store %abs : !scl.address<!scl.real> = [[NEG]]
    abs := -in;

// CHECK:       } else {
// CHECK-DAG:   [[IN:%[0-9]+]] = scl.load %in
// CHECK:       [[GT:%[0-9]+]] = scl.cmpgt [[IN]], [[C0]]
// CHECK:       scl.if [[GT]]
  elsif in > 0.0 then

// CHECK-DAG:   [[IN:%[0-9]+]] = scl.load %in
// CHECK:       scl.store %abs : !scl.address<!scl.real> = [[IN]]
    abs := in;

// CHECK:       } else {
  else

// CHECK:       scl.store %abs : !scl.address<!scl.real> = [[C0]]
    abs := 0.0;

  end_if;

// CHECK:       scl.return.value %abs : !scl.address<!scl.real>
end_function
