// RUN: sclang-gen --emit=mlir %s | sclang-gen -x mlir --emit=mlir | FileCheck %s

// CHECK-LABEL: scl.function @abs(%arg0: !scl.int {scl.name = "in"}) -> !scl.int
// CHECK-DAG:   %abs = scl.tmpvar "abs" : !scl.address<!scl.int>
function abs : int

// CHECK-DAG:   %in = scl.tmpvar "in" : !scl.address<!scl.int>
// CHECK-DAG:   scl.store %in : !scl.address<!scl.int> = %arg0 : !scl.int
var_input
 in : INT;
end_var;

begin
// CHECK-DAG:   [[C0:%c0[_0-9]*]] = scl.constant 0 : i16 -> !scl.int
// CHECK-DAG:   [[IN:%[0-9]+]] = scl.load %in
// CHECK-DAG:   [[LT:%[0-9]+]] = scl.cmplt [[IN]], [[C0]]
// CHECK: scl.if [[LT]]
  if in < 0 then

// CHECK-DAG:   [[IN:%[0-9]+]] = scl.load %in
// CHECK-DAG:   [[NEG:%[0-9]+]] = scl.negate [[IN]]
// CHECK:       scl.store %abs : !scl.address<!scl.int> = [[NEG]]
    abs := -in;

// CHECK:       } else {
// CHECK-DAG:   [[IN:%[0-9]+]] = scl.load %in
// CHECK-DAG:   [[GT:%[0-9]+]] = scl.cmpgt [[IN]], [[C0]]
// CHECK:       scl.if [[GT]]
  elsif in > 0 then

// CHECK-DAG:   [[IN:%[0-9]+]] = scl.load %in
// CHECK:       scl.store %abs : !scl.address<!scl.int> = [[IN]]
    abs := in;

// CHECK:       } else {
  else

// CHECK:       scl.store %abs : !scl.address<!scl.int> = [[C0]]
    abs := 0;

  end_if;

// CHECK:       scl.return.value %abs : !scl.address<!scl.int>
end_function
