// RUN: sclang-gen --emit=mlir %s | FileCheck %s

// CHECK-LABEL: scl.function @abs(%arg0: !scl.int {scl.name = "in"}) -> !scl.int
// CHECK-DAG:   %abs = scl.tmpvar "abs" : !scl.address<!scl.int>
function abs : int

var_input
 in : INT;
end_var;

begin
// CHECK-DAG:   [[C0:%c0[_0-9]*]] = scl.constant 0 : i16 -> !scl.int
// CHECK-DAG:   [[LT:%[0-9]+]] = scl.cmplt %arg0, [[C0]]
// CHECK: scl.if [[LT]]
  if in < 0 then

// CHECK-DAG:   [[NEG:%[0-9]+]] = scl.negate %arg0
// CHECK:       scl.store %abs : !scl.address<!scl.int> = [[NEG]]
    abs := -in;

// CHECK:       scl.end
// CHECK-DAG:   [[GT:%[0-9]+]] = scl.cmpgt %arg0, [[C0]]
// CHECK:       scl.if [[GT]]
  elsif in > 0 then

// CHECK:       scl.store %abs : !scl.address<!scl.int> = %arg0
    abs := in;

// CHECK:       scl.end
  else

// CHECK:       scl.store %abs : !scl.address<!scl.int> = [[C0]]
    abs := 0;

// CHECK:       scl.end
  end_if;

// CHECK:       scl.return.value %abs : !scl.address<!scl.int>
end_function
