// RUN: sclang-gen --emit=mlir %s | FileCheck %s

// CHECK-LABEL: scl.function @callee
function callee : int

var_input
  a : int;
  b : int;
end_var

begin

  callee := a * 2 + b;

end_function


// CHECK-LABEL: scl.function @caller
function caller : int

begin

// CHECK-DAG: [[C2:%c2[_0-9]*]] = scl.constant 2 : i16
// CHECK-DAG: [[C3:%c3[_0-9]*]] = scl.constant 3 : i16
// CHECK-DAG: scl.call.fc @callee([[C2]], [[C3]]) : (!scl.int, !scl.int) -> !scl.int
  caller := callee(2, 3);

end_function
