// RUN: sclang-gen --emit=mlir %s | sclang-gen -x mlir --emit=mlir --opt | FileCheck %s

// CHECK-LABEL: scl.function @callee_1
function callee_1 : int

var_input
  a : int;
end_var

begin

  callee_1 := a * 2;

end_function


// CHECK-LABEL: scl.function @caller_1
function caller_1 : int

begin

// CHECK-DAG: [[C1:%c1[_0-9]*]] = scl.constant 1 : i16
// CHECK-DAG: scl.call.fc @callee_1([[C1]]) {argNames = ["a"]} : (!scl.int) -> !scl.int
  caller_1 := callee_1(1);

end_function


// CHECK-LABEL: scl.function @callee_2
function callee_2 : int

// CHECK: %a = scl.tmpvar "a" : !scl.address<!scl.int>
// CHECK: %b = scl.tmpvar "b" : !scl.address<!scl.int>
var_input
  a : int;
  b : int;
end_var

begin

// CHECK-DAG: [[A:%[0-9]+]] = scl.load %a
// CHECK-DAG: [[B:%[0-9]+]] = scl.load %b
// CHECK-DAG: [[X:%[0-9]+]] = scl.call.fc @callee_1([[B]]) {argNames = ["a"]} : (!scl.int) -> !scl.int
// CHECK-DAG: [[Y:%[0-9]+]] = scl.add [[A]], [[X]]
// CHECK-DAG: scl.store %callee_2 : !scl.address<!scl.int> = [[Y]]
  callee_2 := a + callee_1(a:=b);

end_function


// CHECK-LABEL: scl.function @caller_2
function caller_2 : int

begin

// CHECK-DAG: [[C2:%c2[_0-9]*]] = scl.constant 2 : i16
// CHECK-DAG: [[C3:%c3[_0-9]*]] = scl.constant 3 : i16
// CHECK-DAG: scl.call.fc @callee_2([[C2]], [[C3]]) {argNames = ["a", "b"]} : (!scl.int, !scl.int) -> !scl.int
  caller_2 := callee_2(a:=2, b:=3);

end_function


// CHECK-LABEL: scl.function @caller_2_reorder
function caller_2_reorder : int

begin

// CHECK-DAG: [[C2:%c2[_0-9]*]] = scl.constant 2 : i16
// CHECK-DAG: [[C3:%c3[_0-9]*]] = scl.constant 3 : i16
// CHECK-DAG: scl.call.fc @callee_2([[C2]], [[C3]]) {argNames = ["a", "b"]} : (!scl.int, !scl.int) -> !scl.int
  caller_2_reorder := callee_2(b:=3, a:=2);

end_function
