# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get -yq --no-install-suggests --no-install-recommends install ninja-build
      
    - name: Check-out llvm-project
      uses: actions/checkout@v2
      with:
        repository: llvm/llvm-project
    - name: Check-out sclang
      uses: actions/checkout@v2
      with:
        path: sclang

    - name: Prepare build environment
      run: mkdir build && cd build && cmake -GNinja ../llvm
            -DLLVM_EXTERNAL_PROJECTS=sclang -DLLVM_ENABLE_PROJECTS="sclang;mlir"
            -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --target sclang
    - name: Test
      run: cmake --build build --target check-sclang
